language: perl
perl:
  - "5.22"

notifications:
  email:
    recipients:
      - olaf@wundersolutions.com
    on_success: always
    on_failure: always
  irc: "irc.perl.org#metacpan-travis"

env:
  global:
    # We use a non-standard port to avoid trashing production
    # but travis will have it running on the standard port.
    - ES=localhost:9200

    # Instantiate Catalyst models using metacpan_server_testing.conf
    - METACPAN_SERVER_CONFIG_LOCAL_SUFFIX=testing
  matrix:
    - USE_CPANFILE_SNAPSHOT=true
    - USE_CPANFILE_SNAPSHOT=false

matrix:
  allow_failures:
    - env: USE_CPANFILE_SNAPSHOT=false

# libgmp-dev required by Net::OpenID::Consumer
# postgresql-server-dev-all is required by DBD::Pg

addons:
  apt:
    packages:
    - libgmp-dev
    - postgresql-server-dev-all

before_install:
  - sudo mkdir -p /etc/elasticsearch/scripts/ && sudo curl -O -L https://github.com/metacpan/metacpan-puppet/raw/master/modules/metacpan_elasticsearch/files/etc/scripts/prefer_shorter_module_names_400.groovy > /tmp/prefer_shorter_module_names_400.groovy && sudo cp /tmp/prefer_shorter_module_names_400.groovy /etc/elasticsearch/scripts/

  - sudo service elasticsearch stop && curl -O -L https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.4.3.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.3.deb && sudo service elasticsearch start

  - sudo service elasticsearch restart

  #- cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n Carton
  - cpanm -n App::cpm

  # Carton refuses to update Safe.pm to the version specified in the cpanfile and the
  # version that's core in 5.16 is too old (it fails to work with Devel::Cover).
  - cpanm -n Safe@2.35

install:
  - 'cpm install `test "${USE_CPANFILE_SNAPSHOT}" = "false" && echo " --resolver metadb" || echo " --resolver snapshot"`'

before_script:
  - "perl -i -pe 's/(servers :)9900/localhost:9200/' metacpan_server_testing.conf"

script:
  # Devel::Cover isn't in the cpanfile
  # but if it's installed into the global dirs this should work.
  #- HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,local carton exec prove -It/lib -lr -j 2 t
  - carton exec prove -It/lib -lr -j 2 t

after_success:
#  - cover -report coveralls

#after_failure:
#  - cat ~/.cpanm/build.log

services:
  - elasticsearch

# caching /local should save about 5 minutes in module install time
cache:
  directories:
    - local
